scenario: simple_spread_v2 # choose from simple_spread_v2, simple_reference_v2, simple_speaker_listener_v3
continuous_actions: True
# 아래서부터 내가 새로 추가한 것
map_size: 1
N: 3  # 3기준 900이 좋아보임 600도 시도중
max_cycles: 500
use_wall: True
lifelong: True
sparse_reward: False
semi_sparse_reward: False
agent_size: 0.04
landmark_size: 0.03
agent_wise_distance: False