# Network Architecture Parameters
network:
  # input feature dimension
  input_dim: 2
  # latent dimension
  latents_dim: 128
  # output dimension
  output_dim: 64
  # activation function
  activation_function: relu
  # use independent nets
  use_independent_nets: True
  # use central SD
  use_central_SD: False

tdd:
  # discount factor
  tdd_discount: 0.99

# Training Parameters
train:
  # total number of learning steps of warmup
  warmup_steps: 8000 # 5000을 권장
  # total number of learning steps of learning
  learning_steps: 8000 # 4로 해보자
  # warmup logging interval
  warmup_logging_interval: 1000
  # learning logging interval
  learning_logging_interval: 1000
  # batch size for training
  batch_size: 1024 # 512가 원래 값
  # coeff stop ratio 클수록 빨리 멈춘다. ex) 1/2 steps에 멈추기. 0으로 설정하면 감소 안 한다.
  coeff_stop_ratio: 0
  # coeff magnitude
  coeff_magnitude: 10
  # learning rate
  learning_rate: 1e-3
  # coeff for inter-agent intrinsic reward
  coeff_inter_agent_int_rew: 0
  # off the extrinsic reward
  off_extrinsic_reward: True
  # update interval of rollout history
  update_interval_of_rollout_history: 6000 # 3000 * 800 = 2400000
  # use synthetic data
  use_synthetic_data: False
  # number of trajectories for synthetic data
  n_trajs_for_synthetic_data: 1000
  # use reverse update
  use_reverse_update: False
  # use only one buffer
  use_one_buffer: False
  
  
  # use suppression reward
  use_suppression_reward: False
  # use state entropy
  use_state_entropy: True
  # use actor entropy
  use_actor_entropy: True
  # max historical samples
  max_historical_samples: 4000
  # max batch size
  max_batch_size: 1024
  # default k value
  default_k_value: 7
  # tdd with mean state
  tdd_with_mean_state: False

# Logging Parameters
logging:
  # enable TDD logging
  enable_tdd_logging: False
  # enable performance monitoring logs
  enable_performance_logs: False