# Network Architecture Parameters
network:
  # input feature dimension
  input_dim: 2
  # latent dimension
  latents_dim: 128
  # output dimension
  output_dim: 64
  # activation function
  activation_function: relu
  # use independent nets
  use_independent_nets: True
  # use full partial observation
  use_full_p_obs: True
  # use intra obs
  use_intra_obs: False
  # use partial obs without others
  use_p_obs_without_others: False

tdd:
  # discount factor
  tdd_discount: 0.99

# Training Parameters
train:
  # total number of learning steps of warmup
  warmup_steps: 5000 # 8000을 권장하나 이젠 5000도 되지 않을까 싶다
  # total number of learning steps of learning
  learning_steps: 6000  # 본격적으로 온라인학습할 때 한 번 학습할때마나 learning_steps만큼 도는거다.
  # warmup logging interval
  warmup_logging_interval: 1000
  # learning logging interval
  learning_logging_interval: 1000
  # batch size for training
  batch_size: 1024 # 512가 원래 값
  # coeff stop ratio 클수록 빨리 멈춘다. ex) 1/2 steps에 멈추기. 0으로 설정하면 감소 안 한다.
  coeff_stop_ratio: 0
  # coeff magnitude
  coeff_magnitude: 10
  # learning rate
  learning_rate: 1e-3
  
  # use updated inter-agent intrinsic reward
  use_updated_inter: False
  # coeff for inter-agent intrinsic reward
  coeff_inter_agent_int_rew: 0
  # off the extrinsic reward
  off_extrinsic_reward: True
  # update interval of rollout history
  update_interval_of_rollout_history: 5000 # 3000 * 800 = 2400000 즉 이 숫자만큼 히스토리가 쌓여야 tdd학습이 진행된다.
  # use synthetic data
  use_synthetic_data: False
  # number of trajectories for synthetic data
  n_trajs_for_synthetic_data: 1000
  # use reverse update
  use_reverse_update: False
  # use only one buffer
  use_one_buffer: False
  
  # use suppression reward
  use_suppression_reward: False
  # use state entropy
  use_state_entropy: False
  # use actor entropy
  use_actor_entropy: True
  # max historical samples
  max_historical_samples: 5000
  # max batch size
  max_batch_size: 1024
  # default k value
  default_k_value: 11

# Logging Parameters
logging:
  # turn on/off graph logging
  enable_graph_logging: False
  # turn on/off logger logging
  enable_logger_logging: False
  # tb_plot logging
  tb_plot: True
  # wandb logging
  wandb: False

wm:
  # use wm
  use_wm: True
  # number of wm updates
  n_wm_updates: 120
  batch_size: 32
  buffer_size: 5000

  # 모델 파라미터
  dyn_stoch: 16
  dyn_deter: 128
  dyn_hidden: 128
  dyn_rec_depth: 1
  dyn_discrete: False  # 이게 16이면 더 풍부한 표현력을 가지게 된다는데 잘 모르겠다. dist = torchd.independent... OneHot이라는데 그게 진짜 좋으려나?
  act: SiLU
  norm: True
  dyn_mean_act: "none"
  dyn_std_act: sigmoid2
  dyn_min_std: 0.1
  unimix_ratio: 0.01
  initial: zeros
  precision: 32 # 모델의 계산 정밀도를 설정. 16이면 FP16으로써 메모리가 절약되고 속도가 향상된다.
  
  grad_heads: ['decoder']
  decode_role: False
  model_lr: 0.0001
  opt_eps: 1e-8
  grad_clip: 1000
  weight_decay: 0.0
  opt: adam
  
  kl_free: 1.0
  dyn_scale: 0.5
  rep_scale: 0.1

  dyna_tau: 0.005

  encoder:
    act: SiLU
    mlp_keys: vector_obs
    mlp_layers: 2
    mlp_units: 128
    norm: True
    symlog_inputs: True
  
  decoder:
    act: SiLU
    mlp_keys: vector_obs
    mlp_layers: 2
    mlp_units: 128
    norm: True
    outscale: 1.0
    vector_dist: symlog_mse